### PR TITLE
Various documentation improvements

### PR DESCRIPTION
**Pull request by gregrs-uk**
I've edited `other.R` and `lump.R` but I believe some other files need generating using `roxygen2` and `pkgdown`.

### CODE REVIEW

**Comment by gregrs-uk** [comment]
I've now used `roxygen2` and `pkgdown` to update the files in the `man` and `docs` directories. Running `roxygenise` and `pkgdown` caused a lot of other small changes but I've only committed those relevant to the changes I've made.

**Comment by gregrs-uk** [comment]
Some more improvements to documentation.

Used `pkgdown` and `roxygen2` ver 6.0.1.9000 but only committed relevant changes and **didn’t** update `DESCRIPTION` with `roxygen2` version (see `RoxygenNote`)

**Comment by hadley** [comment]
Thanks! For future reference, it's better to only re-`document()`, but not rebuild the package website.

**Comment by gregrs-uk** [comment]
Thanks @hadley. Do the HTML files in `docs/reference` get updated another way?

**Comment by hadley** [comment]
Generally I think we’ll do once per release

**Comment by gregrs-uk** [comment]
Good to know, thanks.

**Pull request merged**
